services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: taskhub_php
    volumes:
      - ./backend:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - taskhub
    command: php artisan serve --host=0.0.0.0 --port=8000

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: taskhub_node
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8000
    ports:
      - "8080:8080"
    networks:
      - taskhub

  db:
    image: mysql:8.0
    container_name: taskhub_db
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskhub
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taskhub

  redis:
    image: redis:alpine
    container_name: taskhub_redis
    ports:
      - "6379:6379"
    networks:
      - taskhub

networks:
  taskhub:

volumes:
  db_data:
  node_modules:
  vendor_data:
